### ISSUE TITLE
Can't connect to XBOX ONE bluetooth controller

### ISSUE THREAD

**Issue by shulthz** [shantigilbert/EmuELEC#37] opened 2019-08-05 08:12 UTC
Can't connect to XBOX ONE bluetooth controller with 'bluetoothctl'.

`Failed to connect: org.bluez.Error.Failed`

PHICOMM N1 
S905D

**Comment by shantigilbert** [comment] 2019-08-06 08:41
Please check the wiki for Bluetooth instructions. I have one question how did you manage to boot up the phincomm? #27 is having problems with the same device.

**Comment by shulthz** [comment] 2019-08-06 11:53
> 
> 
> Please check the wiki for Bluetooth instructions. I have one question how did you manage to boot up the phicomm? #27 is having problems with the same device.

I think he can get the answer from below：
https://right.com.cn/forum/thread-323198-1-1.html

I followed the wiki for Bluetooth instructions，but failled.

**Comment by shantigilbert** [comment] 2019-10-28 17:50
Can you try with the new version? on the main menu under controllers you should see an option to connect to Bluetooth

**Comment by shantigilbert** [comment] 2019-11-07 17:44
No reply for 10 days, closing issue. Feel free to reopen it again if the problem is still there

**Closed by shantigilbert** 2019-11-07 17:44 UTC

**Comment by shulthz** [comment] 2019-11-14 10:47
It's very hard to download the the new release in China, i will try it when dowload it~~!
